### ISSUE TITLE
Cross Origin Issue with Docker running on local instance

### ISSUE THREAD

**Issue by rahulmr** [pishangujeniya/kite-helper#9]
**Describe the bug**
While trying to login I am getting Cross Origin issue for localhost

**To Reproduce**
Open localhost url and try to login with Zerodha credentials

**Expected behavior**
Documentation on how to work with Cross Domain Origin must be explained

![2022-11-23](https://user-images.githubusercontent.com/10260232/203421821-343c10fd-488f-474f-aa53-a26a5950f7d9.png)

**Comment by rahulmr** [comment]
```
Request URL: http://localhost:8080/api/kite/login
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: [::1]:8080
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Origin: *
Content-Type: application/problem+json; charset=utf-8
Date: Tue, 22 Nov 2022 21:12:19 GMT
Server: Kestrel
Transfer-Encoding: chunked
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 61
Content-Type: application/json
Host: localhost:8080
observe: response
Origin: http://localhost:8080
Referer: http://localhost:8080/account/login
sec-ch-ua: "Microsoft Edge";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52
```

**Comment by pishangujeniya** [comment]
@rahulmr  With correct credentials we are able to login, I guess you are providing incorrect credentials.
![image](https://user-images.githubusercontent.com/25280661/203458954-dcbbe4ab-43e9-4ba9-8719-f0a39b068348.png)

> Tested with fresh pull of Docker image.

**Comment by pishangujeniya** [comment]
HI @rahulmr ,
I have updated docker repository with proper error messages.
Either you first delete your local docker image and re-pull from latest,
or you can use this specific version of docker image `docker pull pishangujeniya/kite-helper:1.1`

[Release Changelog](https://github.com/pishangujeniya/kite-helper/releases/tag/v1.1)

**Comment by rahulmr** [comment]
@pishangujeniya Thanks for quick fix. I will check out.

**Comment by pishangujeniya** [comment]
@rahulmr Please share if it helps you. Sharing is caring.

❤️OpenSource

**Comment by rahulmr** [comment]
Yes, Actually understood the issue now. You login works only with App Code which is generated from Zerodha Kite Android App. In my case, I was trying to use TOTP generated using python code pyotp by configuring external TOTP at zerodha end. So finally I was able to work with App Code from Android App. May be you can try to fix this for TOTP coming from External generator. Below is the code for the generating TOTP using python.

```python
import pyotp
otp = pyotp.TOTP("22Z5JNTNPWAKRDYOI4AEHEONXPCU6Y3Y")
otp.now()
```

**Comment by pishangujeniya** [comment]
@rahulmr Thanks for information, I have mentioned that label of input box as App Code due to that reason only.

_On another note, thanks for the code, hope so that code sample you provided in above comment, is not containing any secret of your personal account._

**Comment by rahulmr** [comment]
No worries @pishangujeniya , the secret is old one.
